### ISSUE TITLE
How do I run this project

### ISSUE THREAD

**Issue by KiraEzy** [Magolor/hoi4dev#1]
How do I run this project?

**Comment by Magolor** [comment]
I have updated the README file. Feel free to provide feedback if you have any confusion.

If you are comfortable working with Python. I'm considering further publicizing the entire source code of my ongoing mod project in future weeks or months.

**Comment by KiraEzy** [comment]
Thanks a lot, I've successfully installed the libary on window with following script in powershell below
```
# Set the MAGICK_HOME environment variable
$env:MAGICK_HOME = "C:\Program Files\ImageMagick-7.1.0-Q16-HDRI"

# Add ImageMagick's bin directory to the PATH
$env:PATH = "$env:MAGICK_HOME\bin;$env:PATH"

# Set PDOC_ALLOW_EXEC environment variable
$env:PDOC_ALLOW_EXEC = 1

# Run pdoc to generate documentation in Google style
pdoc -d google --output-dir doc hoi4dev

# Initialize configuration for hoi4dev
python -c "from hoi4dev import init_config; init_config()"

# Check the version of hoi4dev and confirm successful installation
python -c "import hoi4dev; from pyheaven import GREEN; print(GREEN(f'hoi4dev version {hoi4dev.__version__} successfully installed!'))"`
```
Would it be ok for me to make a PR on adding this window installation script to I've submit a PR for this Isuue by adding a install script for window.

**Comment by Magolor** [comment]
Thank you so much for your help!

In the near future, I will show more examples of using hoi4dev and improve the documentation.
Feel free to ask questions or contribute more to the project.
